version: "3.8"

services:
  robot-config-ui:
    user: root
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8089:8089"
    volumes:
      - ./:/app
      - /services:/services
      - /var/run/docker.sock:/var/run/docker.sock
